repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.9
    stages: [commit]
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    stages: [commit]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    stages: [commit]
- repo: https://github.com/pycqa/pylint
  rev: v2.13.7
  hooks:
  - id: pylint
    files: ^data_harmonization/
    stages: [commit]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
  - id: mypy
    exclude: ^(tests|docs)/
    stages: [commit]