name: data-harmonization

channels:
  - https://conda.anaconda.org/conda-forge
  -
dependencies:
# conda installs should be used where possible especially for any packages that need to be compiles
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - pip
  - pytest
  - pytest-cov
  - pyarrow
  - scipy
  - statsmodels
  - python-dotenv
  - configparser
  - dataclasses
  - python-levenshtein
  - metaphone
  - pyspark
  - SQLAlchemy
  - netifaces
  - pip:
    - sphinx-autodoc-annotation
    - datamodel-code-generator
    - pydantic
    - clean-text[gpl]
    - jaro-winkler
    - mysql_connector_repackaged
    - findspark
    - -e .


