name: data-harmonization

channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
# conda installs should be used where possible especially for any packages that need to be compiles
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - pip
  - pytest
  - pytest-cov
  - pyarrow
  - scipy
  - statsmodels
  - python-dotenv
  - configparser
  - dataclasses
  - python-levenshtein
  - metaphone
  - pyspark==3.3.0
  - SQLAlchemy==1.4.27
  - netifaces==0.11.0
  - MySQLdb
  - graphframes==0.6
  - findspark==2.0.1
  - sphinx-autobuild==2021.3.14
  - sphinx-rtd-theme==1.0.0
  - sphinx==5.1.1
  - myst-parser==0.18.1
  - pip:
    - sphinx-autodoc-annotation
    - datamodel-code-generator
    - pydantic
    - clean-text[gpl]
    - jaro-winkler
    - mysql_connector_repackaged==0.3.1
    - mysql-connector-python