openapi: "3.0.0"
info:
  version: 1.0.0
  title: Data Class Generator
  license:
    name: Tiger Analytics
servers:
  - url: http://dataharmonization.swagger.io/v1
components:
  schemas:
    Gender:
      properties:
        gender_field:
          type: str
    Name:
      properties:
        name:
          type: str
    Address:
      properties:
        city:
          type: str
        zipcode:
          type: str
        address:
          type: str
    Email:
      properties:
        email:
          type: str
    Contact:
      properties:
        country_code:
          type: str
        contact_no:
          type: str
    Entity1:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string
        source:
          type: string
        gender:
          type: string
    Entity2:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string
        source:
          type: string
        gender:
          type: string
    RawEntity:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          $ref: "#/components/schemas/Name"
        address:
          type: string
          $ref: "#/components/schemas/Address"
        gender:
          type: string
          $ref: "#/components/schemas/Gender"
        source:
          type: string