openapi: "3.0.0"
info:
  version: 1.0.0
  title: Data Class Generator
  license:
    name: Tiger Analytics
servers:
  - url: http://dataharmonization.swagger.io/v1
components:
  schemas:
    Name:
      properties:
        name:
          type: str
    Address:
      properties:
        city:
          type: str
        state:
          type: str
        zipcode:
          type: str
        address:
          type: str
    RawEntity:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          items:
            $ref: "#/components/schemas/Name"
        address:
          type: array
          items:
            $ref: "#/components/schemas/Address"
        source:
          type: string
    CleansedRawEntity:
      properties:
        entity:
          type: array
          items:
            $ref: "#/components/schemas/RawEntity"