# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2022-08-24T13:29:45+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class RawEntity(BaseModel):
    id: int
    name: Optional[str] = None
    city: Optional[str] = None
    address: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    source: Optional[str] = None


class CleansedRawEntity(BaseModel):
    id: int
    name: str
    city: str
    address: str
    state: str
    zipcode: str
    source: str
