# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2022-09-08T16:25:56+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class Gender(BaseModel):
    gender_field: Optional[Any] = None


class Name(BaseModel):
    name: Optional[Any] = None


class Address(BaseModel):
    city: Optional[Any] = None
    zipcode: Optional[Any] = None
    address: Optional[Any] = None # postaladdresses


class Entity1(BaseModel):
    id: int
    name: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    source: Optional[str] = None
    gender: Optional[str] = None


class Entity2(BaseModel):
    id: int
    name: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    source: Optional[str] = None
    gender: Optional[str] = None


class RawEntity(BaseModel):
    id: int
    name: Optional[Name] = None
    address: Optional[Address] = None
    gender: Optional[Gender] = None
    source: Optional[str] = None
