# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2022-08-24T22:45:56+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class Name(BaseModel):
    name: Optional[Any] = None


class Address(BaseModel):
    city: Optional[Any] = None
    state: Optional[Any] = None
    zipcode: Optional[Any] = None
    address: Optional[Any] = None


class RawEntity(BaseModel):
    id: int
    name: Optional[List[Name]] = None
    address: Optional[List[Address]] = None
    source: Optional[str] = None


class CleansedRawEntity(BaseModel):
    entity: Optional[List[RawEntity]] = None
