# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2022-09-14T09:39:54+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel


class Gender(BaseModel):
    gender_field: Optional[Any] = None


class Name(BaseModel):
    Name: Optional[Any] = None


class Address(BaseModel):
    City: Optional[Any] = None
    Zip: Optional[Any] = None
    Address: Optional[Any] = None


class Email(BaseModel):
    email: Optional[Any] = None


class Contact(BaseModel):
    country_code: Optional[Any] = None
    contact_no: Optional[Any] = None


class Entity1(BaseModel):
    id: int
    name: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    source: Optional[str] = None
    gender: Optional[str] = None


class Entity2(BaseModel):
    id: int
    name: Optional[str] = None
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zipcode: Optional[str] = None
    source: Optional[str] = None
    gender: Optional[str] = None

class RawEntity(BaseModel):
    name: Optional[Name] = None
    address: Optional[Address] = None
    gender: Optional[Gender] = None
    source: Optional[str] = None
    age: Optional[int] = 0
