name: data-harmonization-benchmark

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - xlrd
  #
  - pyspark
  - netifaces==0.11.0
  # - mysql-python
  - pip:
      - dedupe
      - pandas-dedupe
      - unidecode
      - dedupe-hcluster
      - rlr
